version: '3.4'
services:
  mysql:
    image: mysql:8.0.29
    container_name: mysql-service
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=suhang666
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_bin', '--transaction-isolation=READ-COMMITTED', '--innodb_log_file_size=256M', '--max_allowed_packet=256M','--log_bin_trust_function_creators=1']
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always
    networks:
      - network-bridge

networks:
  network-bridge:
    driver: bridge

volumes:
  mysql_data:
    external: false